platform:ios, '8.0'

target ‘SmartLamp’ do
#  pod 'AFNetworking', '~> 3.0.4'
  #pod 'HYBNetworking', '~> 2.0.1'
#  pod 'MJRefresh', '~> 3.1.0'
  #pod 'BaiduMapKit'
  #pod 'YYText'
  pod 'SCLAlertView-Objective-C', '~> 1.0.3'
  #pod 'IQKeyboardManager', '~> 4.0.3'
  #pod 'MJExtension', '~> 3.0.10'
  #pod 'SDWebImage', '~> 3.7.6'
  
end
